// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDt8poG1Nu_1bsRnDR_MXjxSfwqPkGJYUY',
    appId: '1:1004286783433:web:c1daadf68441e892488218',
    messagingSenderId: '1004286783433',
    projectId: 'order-product-a893a',
    authDomain: 'order-product-a893a.firebaseapp.com',
    storageBucket: 'order-product-a893a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCm7REhXX015kEk5Z2N-5Dciva9mRTWCBs',
    appId: '1:1004286783433:android:05cdece5b9cb9763488218',
    messagingSenderId: '1004286783433',
    projectId: 'order-product-a893a',
    storageBucket: 'order-product-a893a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAngQwfUse4w0rZsIF6xY0r4MUPREKUloI',
    appId: '1:1004286783433:ios:8d6b695e7776c4af488218',
    messagingSenderId: '1004286783433',
    projectId: 'order-product-a893a',
    storageBucket: 'order-product-a893a.appspot.com',
    iosBundleId: 'com.example.productorder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAngQwfUse4w0rZsIF6xY0r4MUPREKUloI',
    appId: '1:1004286783433:ios:8d6b695e7776c4af488218',
    messagingSenderId: '1004286783433',
    projectId: 'order-product-a893a',
    storageBucket: 'order-product-a893a.appspot.com',
    iosBundleId: 'com.example.productorder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDt8poG1Nu_1bsRnDR_MXjxSfwqPkGJYUY',
    appId: '1:1004286783433:web:67e8519677ec0d25488218',
    messagingSenderId: '1004286783433',
    projectId: 'order-product-a893a',
    authDomain: 'order-product-a893a.firebaseapp.com',
    storageBucket: 'order-product-a893a.appspot.com',
  );
}
